{
 "title": "Loki / Dashboard",
 "description": "Loki dashboard with quick search and timeline.",
 "tags": [ "Loki" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Debug",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"fastify\"} | detected_level=\"debug\"[$__range]))"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"fastify\"} | detected_level=\"info\"[$__range]))"
    }
   ]
  },
  {
   "title": "Warn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"fastify\"} | detected_level=\"warn\"[$__range]))"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"fastify\"} | detected_level=\"error\"[$__range]))"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (rate({service_name=\"fastify\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"fastify\"} |= ``"
    }
   ]
  }
 ]
}